services:
  mysql:
    image: mysql:8.4.9
    container_name: order-mysql
    restart: always
    environment:
      MYSQL_DATABASE: order-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: app
    image: order-image
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql-data: