server.port=8080

spring.datasource.url=jdbc:mysql://mysql:3306/order-db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=34.68.120.33
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://34.10.42.179:8761/eureka/

server.allow.id=34.41.152.3